memory_limit=1024M
upload_max_filesize=64G
post_max_size=64G
max_execution_time=7200
max_input_time=7200
output_buffering=0
zlib.output_compression=Off
opcache.enable=1
opcache.memory_consumption=256
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=20000
opcache.revalidate_freq=60
apc.enabled=1
apc.shm_size=128M

; Redis authentication for PHP sessions
session.save_path = "tcp://redis:6379?auth=79qMMgHrC7YYrQyFHBFX5jwzl2BLmlxe"
