/var/log/nginx/metrics/*.log {
    daily
    missingok
    rotate 14
    maxsize 20M
    compress
    delaycompress
    notifempty
    create 0640 www-data adm
    sharedscripts
    postrotate
        invoke-rc.d nginx rotate >/dev/null 2>&1
    endscript
}

/var/log/nginx/incident-correlation/*.log {
    daily
    missingok
    rotate 7
    maxsize 20M
    compress
    delaycompress
    notifempty
    create 0640 www-data adm
    sharedscripts
    postrotate
        invoke-rc.d nginx rotate >/dev/null 2>&1
    endscript
}
